"""auto-votes

Revision ID: e8ed2444172f
Revises: a2fbe398da93
Create Date: 2025-10-11 14:31:37.684053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ed2444172f'
down_revision: Union[str, Sequence[str], None] = 'a2fbe398da93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('votes_user_id', sa.Integer(), nullable=False),
    sa.Column('votes_posts_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['votes_posts_id'], ['groceries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['votes_user_id'], ['users_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('votes_user_id', 'votes_posts_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
